import { version } from '~/package';
import Misc from '~/Misc';
import Graphics from '~/Graphics';
import Types from '~/Types';
import Browser from '~/Browser';
import Datetime from '~/Datetime';
import Random from '~/Random';
import Collection from '~/Collection';
import Template from '~/Template';
import Color from '~/Color';
import IDimensions from '~/interfaces/IDimensions';
import ICoordinate from '~/interfaces/ICoordinate';
import IRect from '~/interfaces/IRect';
export { version, Misc, Graphics, Types, Browser, Datetime, Random, Collection, Template, Color, IDimensions, ICoordinate, IRect };
